name: 'SGCC Electricity WEB'
version: '0.0.4'
slug: 'sgcc_electricity_web'
description: '国家电网电力获取-web server端'
url: 'https://github.com/Javedhd/sgcc_electricity_web'
arch:
  - 'aarch64'
  - 'amd64'
host_network: false
startup: 'application'
boot: 'auto'
init: false
ports:
  8080/tcp: 8080
map:
  - type: addon_config 
    read_only: False
image: 'crpi-djdbf2lzhff05hy6.cn-beijing.personal.cr.aliyuncs.com/javedhb/sgcc_electricity_web'
options:
  electricity:
    phone_number: null 
    password: null
    deiver_impltcity_wait_time: 60
    retry_times_limit: 5
    login_expected_time: 60
    retry_wait_time_offset_unit: 10
    data_retention_days: 7
    ignore_user_id: []

  db:
    name: 'homeassistant.db'

  logger:
    level: 'info'

schema:
  electricity:
    phone_number: 'str' 
    password: 'password'
    deiver_impltcity_wait_time: 'int'
    retry_times_limit: 'int'
    login_expected_time: 'int'
    retry_wait_time_offset_unit: 'int'
    data_retention_days: 'int'
    ignore_user_id:
      - 'str?'
    cron_hour: str

  db:
    name: 'str'

  logger:
    level: 'str'
